name: Sync from upstream

on:
  # schedule:
  #   - cron: '*/5 7-20 * * *'

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-app-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync from upstream
        uses: giantswarm/subtree-util@v0.1.2
        with:
          target_github_token: ${{ secrets.ARCHITECT_BOT_GITHUB_REPO_SYNC_TOKEN }}
          target_repository: giantswarm/keda-app
          target_path: helm/keda
          source_tag_wildcard: "v*"
          source_path: keda

